apiVersion: security.kubesonde.io/v1
kind: Kubesonde
metadata:
  name: kubesonde-sample-with-pods
spec:
  namespace: "default"
  # Add fields here
  actions:
    - action: "Allow"
      fromPodSelector: "application1"
      url: "https://www.aalto.fi/fi"
    - action: "Allow"
      fromPodSelector: "application1"
      toPodSelector: "application2"
      port: "80"
    - action: "Deny"
      fromPodSelector: "application1"
      toPodSelector: "nginx-demo"
      port: "443"
    - action: "Allow"
      fromPodSelector: "application1"
      url: "https://www.google.com"
      endpoint: "doodles"
