name: Build and Test frontend

on:
  push:
    branches:
      - dev
    paths:
      - frontend/**
      - .github/**
  pull_request:
    branches:
      - "**"
    paths:
      - frontend/**
      - .github/**

jobs:
  prepare:
    uses: jackap/kubesonde/.github/workflows/frontend_base.yaml@main
