name: Build and test CRD

on:
  push:
    branches:
      - master
      - dev
    paths:
      - crd/**
  pull_request:
    branches:
      - "**"
      - ".github/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Cache dependencies
        uses: actions/cache@preview
        id: cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}

      - name: Build
        working-directory: crd
        run: go build -v ./...

      - name: Test
        working-directory: crd
        run: go test -v ./... -coverprofile cover.out

      - name: Add git safe.directory for container
        run: |
          mkdir -p /home/runner/work/_temp/_github_home
          printf "[safe]\ndirectory = /github/workspace" > /home/runner/work/_temp/_github_home/.gitconfig

      - name: Send coverage results
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: go
          coverage-file: cover.out
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
