name: Build and test CRD

on:
  push:
    branches:
      - master
      - dev
    paths:
      - crd/**
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Cache dependencies
        uses: actions/cache@preview
        id: cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}

      - name: Build
        working-directory: crd
        run: go build -v ./...

      - name: Test
        working-directory: crd
        run: go test -v ./... -coverprofile cover.out
